### ISSUE TITLE
Faile to load application.conf file

### ISSUE THREAD

**Issue by ErezAlster** [ReactiveCouchbase/ReactiveCouchbase-core#72]
Hi

This is my applicaiton.conf file:
couchbase {
  akka {
    timeout=1000
    execution-context {
      fork-join-executor {
        parallelism-factor = 4.0
        parallelism-max = 40
      }
    }
  }
  buckets = [{
    host="127.0.0.1"
    port="8091"
    base="pools"
    bucket="default"
    user=""
    pass=""
    timeout="0"
  }]
}

I'm getting the following error when trying to run my akka code:
2015-11-23 11:53:20.478 INFO com.couchbase.client.vbucket.provider.BucketConfigurationProvider:  Could bootstrap through carrier publication.
2015-11-23 11:53:20.486 INFO com.couchbase.client.CouchbaseConnection:  Added {QA sa=/127.0.0.1:11210, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0} to connect queue
2015-11-23 11:53:20.491 INFO com.couchbase.client.CouchbaseClient:  CouchbaseConnectionFactory{bucket='default', nodes=[http://127.0.0.1:8091/pools], order=RANDOM, opTimeout=2500, opQueue=16384, opQueueBlockTime=10000, obsPollInt=10, obsPollMax=500, obsTimeout=5000, viewConns=10, viewTimeout=75000, viewWorkers=1, configCheck=10, reconnectInt=1100, failureMode=Redistribute, hashAlgo=NATIVE_HASH, authWaitTime=2500}
2015-11-23 11:53:20.544 INFO com.couchbase.client.CouchbaseClient:  viewmode property isn't defined. Setting viewmode to production mode
11:53:20.547 [akka-spray-akka.actor.default-dispatcher-5] INFO  ReactiveCouchbase - Failing on bad JSON structure enabled.

Any idea what can be the problem?

**Comment by mathieuancelin** [comment]
Hi, 

there is no error in the log

**Comment by ErezAlster** [comment]
Sorry, This is the exception

Exception in thread "main" java.lang.NoSuchMethodError: akka.actor.Props$.apply(Lscala/Function0;)Lakka/actor/Props;
	at spray.can.HttpExt.<init>(Http.scala:138)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$2.apply(DynamicAccess.scala:78)
	at scala.util.Try$.apply(Try.scala:161)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:73)
	at akka.actor.ExtensionKey.createExtension(Extension.scala:153)
	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:711)
	at akka.actor.ExtensionId$class.apply(Extension.scala:79)
	at akka.actor.ExtensionKey.apply(Extension.scala:149)
	at akka.io.IO$.apply(IO.scala:30)
	at web.Web$class.$init$(Web.scala:22)
	at Rest$.<init>(Rest.scala:5)
	at Rest$.<clinit>(Rest.scala)
	at Rest.main(Rest.scala)

**Comment by mathieuancelin** [comment]
It seems there is a conflict with versions of akka-actors
